/** Données de démonstration — Casablanca (à remplacer par API réelles plus tard) */

export const DEMO_WEATHER = {
  city: 'Casablanca',
  updatedAt: new Date().toISOString(),
  current: {
    tempC: 22,
    feelsLikeC: 21,
    condition: 'Partiellement nuageux',
    humidity: 68,
    windKmh: 14,
    windDir: 'NO',
    uv: 6,
  },
  forecast: [
    { day: 'Aujourd\'hui', icon: 'partly', high: 23, low: 16, precip: 10 },
    { day: 'Dimanche', icon: 'sun', high: 24, low: 17, precip: 0 },
    { day: 'Lundi', icon: 'cloud', high: 21, low: 15, precip: 30 },
    { day: 'Mardi', icon: 'rain', high: 19, low: 14, precip: 60 },
    { day: 'Mercredi', icon: 'sun', high: 22, low: 15, precip: 5 },
  ],
  drivingTip: 'Vent modéré côté corniche — prudence sur l’autoroute vers Rabat.',
};

export const DEMO_POIS = [
  {
    id: 'hassan-ii',
    name: 'Mosquée Hassan II',
    category: 'Monument',
    district: 'Ain Diab',
    description: 'Architecture emblématique face à l’Atlantique. Visites guidées sur créneaux.',
    open: '9h – 15h (sauf vendredi matin)',
    tag: 'Incontournable',
  },
  {
    id: 'old-medina',
    name: 'Médina & place Mohammed V',
    category: 'Quartier',
    district: 'Centre-ville',
    description: 'Souks, artisanat, cafés. Circulation dense en soirée.',
    open: 'Toute la journée',
    tag: 'Culture',
  },
  {
    id: 'marina',
    name: 'Marina de Casablanca',
    category: 'Loisirs',
    district: 'Casablanca Marina',
    description: 'Promenade, restaurants, vue port. Accès facile depuis la corniche.',
    open: '10h – 23h',
    tag: 'Famille',
  },
  {
    id: 'twin-center',
    name: 'Twin Center',
    category: 'Shopping',
    district: 'Maarif',
    description: 'Tours jumelles, commerces et cafés. Parking souterrain.',
    open: '10h – 22h',
    tag: 'Shopping',
  },
  {
    id: 'parc-ligue',
    name: 'Parc de la Ligue Arabe',
    category: 'Parc',
    district: 'Centre',
    description: 'Espace vert au cœur de la ville, idéal pour une pause.',
    open: '8h – 20h',
    tag: 'Détente',
  },
  {
    id: 'gare',
    name: 'Gare Casa-Voyageurs',
    category: 'Transport',
    district: 'Roches Noires',
    description: 'Hub TGV et trains régionaux. Prévoir délais aux heures de pointe.',
    open: '24h/24',
    tag: 'Transport',
  },
];

export const DEMO_WEBCAMS = [
  {
    id: 'corniche',
    name: 'Corniche Ain Diab',
    zone: 'Front de mer',
    status: 'live',
    thumb: 'corniche',
    note: 'Vue sur la plage et la circulation côté bord de mer.',
  },
  {
    id: 'maarif',
    name: 'Carrefour Maarif',
    zone: 'Maarif',
    status: 'live',
    thumb: 'urban',
    note: 'Flux vers le centre et Bd Zerktouni.',
  },
  {
    id: 'port',
    name: 'Port de Casablanca',
    zone: 'Port',
    status: 'live',
    thumb: 'port',
    note: 'Entrées poids lourds et zone industrielle.',
  },
  {
    id: 'autoroute',
    name: 'Autoroute A5 (sortie Casa)',
    zone: 'Périphérie',
    status: 'live',
    thumb: 'highway',
    note: 'Trafic sortant vers Rabat en fin de journée.',
  },
];

export const DEMO_EVENTS = [
  {
    id: 'e1',
    title: 'Marché artisanal du week-end',
    date: 'Samedi 10h – 18h',
    place: 'Médina — Bab Marrakech',
    type: 'Culture',
    impact: 'Rues piétonnes partielles, stationnement limité.',
  },
  {
    id: 'e2',
    title: 'Match au stade Mohammed V',
    date: 'Dimanche 20h30',
    place: 'Stade Mohammed V',
    type: 'Sport',
    impact: 'Bouchons autour du stade dès 18h.',
  },
  {
    id: 'e3',
    title: 'Salon automobile Casa',
    date: '15 – 18 mai',
    place: 'OFEC — Parc des expositions',
    type: 'Salon',
    impact: 'Afflux véhicules secteur Oulfa / Roches Noires.',
  },
  {
    id: 'e4',
    title: 'Concert en plein air',
    date: 'Vendredi 21h',
    place: 'Anfa Park',
    type: 'Musique',
    impact: 'Fermeture partielle Bd de la Corniche.',
  },
  {
    id: 'e5',
    title: 'Travaux voirie — Roches Noires',
    date: 'Jusqu’au 30 juin',
    place: 'Av. des FAR',
    type: 'Travaux',
    impact: 'Voie réduite, déviations signalées.',
  },
];
